spring:
  application:
    name: revisor-api
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: passwd
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
  cloud:
    function:
      definition: requestContext;requestIaRevision;returnComments;processFeedback
    stream:
      bindings:
        requestMergeRevision-out-0:
          destination: revision-requested-topic
        requestContext-in-0:
          destination: revision-requested-topic
        requestContext-out-0:
          destination: context-retrieved-topic
        requestIaRevision-in-0:
          destination: context-retrieved-topic
        requestIaRevision-out-0:
          destination: comments-generated-topic
        returnComments-in-0:
          destination: comments-generated-topic
        returnComments-out-0:
          destination: process-feedback-topic
        processFeedback-in-0:
          destination: process-feedback-topic
  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG

vcs:
  services:
    github:
#      TODO - fazer o webClient seguir um redirect (302) do https://github.com
      baseUrl: ${GIT_HUB_BASE_URL:https://patch-diff.githubusercontent.com}
      apiBaseUrl:  ${GIT_HUB_API_BASE_URL:https://api.github.com}
      apiVersion:  ${GIT_HUB_API_VERSION:2022-11-28}
      appId: ${APP_ID}
      installationId: ${INSTALLATION_ID}
      pemPath: ${PEM_PATH}

ai:
  services:
    ollama:
      baseUrl: ${OLLAMA_BASE_URL:http://localhost:11434}